spring:
  application:
    name: chat-service
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${id}
            client-secret: ${pw}
            scope:
              - profile_nickname
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id